"""empty message

Revision ID: 818c75bd8cb0
Revises: e269468cde93
Create Date: 2020-10-06 12:17:07.440497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818c75bd8cb0'
down_revision = 'e269468cde93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
