"""empty message

Revision ID: e269468cde93
Revises: 4d20ae3e9088
Create Date: 2020-10-06 11:26:27.450956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e269468cde93'
down_revision = '4d20ae3e9088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('Genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'Genres')
    # ### end Alembic commands ###
